//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheOtherRoles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheOtherRoles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed color succesfully.
        /// </summary>
        internal static string ChangedColorSuccesfully {
            get {
                return ResourceManager.GetString("ChangedColorSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Swap.
        /// </summary>
        internal static string ConfirmSwap {
            get {
                return ResourceManager.GetString("ConfirmSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crewmate Role Settings.
        /// </summary>
        internal static string CrewmateRoleSettings {
            get {
                return ResourceManager.GetString("CrewmateRoleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design by.
        /// </summary>
        internal static string Designby {
            get {
                return ResourceManager.GetString("Designby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sound Effects.
        /// </summary>
        internal static string EnableSoundEffects {
            get {
                return ResourceManager.GetString("EnableSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghosts Can Additionally See Modifier.
        /// </summary>
        internal static string GhostsCanAdditionallySeeModifier {
            get {
                return ResourceManager.GetString("GhostsCanAdditionallySeeModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghosts Can See Roles.
        /// </summary>
        internal static string GhostsCanSeeRoles {
            get {
                return ResourceManager.GetString("GhostsCanSeeRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghosts Can See Votes.
        /// </summary>
        internal static string GhostsCanSeeVotes {
            get {
                return ResourceManager.GetString("GhostsCanSeeVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghosts See Tasks &amp; Other Info.
        /// </summary>
        internal static string GhostsSeeTasksAndOtherInfo {
            get {
                return ResourceManager.GetString("GhostsSeeTasksAndOtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesser.
        /// </summary>
        internal static string Guesser {
            get {
                return ResourceManager.GetString("Guesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &apos;N Seek.
        /// </summary>
        internal static string HideNSeek {
            get {
                return ResourceManager.GetString("HideNSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide N Seek Role Settings.
        /// </summary>
        internal static string HideNSeekRoleSettings {
            get {
                return ResourceManager.GetString("HideNSeekRoleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide N Seek Settings.
        /// </summary>
        internal static string HideNSeekSettings {
            get {
                return ResourceManager.GetString("HideNSeekSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        internal static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostor Role Settings.
        /// </summary>
        internal static string ImpostorRoleSettings {
            get {
                return ResourceManager.GetString("ImpostorRoleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Size\nUsage: /size {amount}.
        /// </summary>
        internal static string InvalidSizeUsage {
            get {
                return ResourceManager.GetString("InvalidSizeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jester Wins.
        /// </summary>
        internal static string JesterWins {
            get {
                return ResourceManager.GetString("JesterWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby Size changed to {LobbyLimit} players.
        /// </summary>
        internal static string LobbySizeChanged {
            get {
                return ResourceManager.GetString("LobbySizeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby Size is already {LobbyLimit}.
        /// </summary>
        internal static string LobbySizeIsTheSame {
            get {
                return ResourceManager.GetString("LobbySizeIsTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovers And Crewmates Win.
        /// </summary>
        internal static string LoversAndCrewmatesWin {
            get {
                return ResourceManager.GetString("LoversAndCrewmatesWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovers Win.
        /// </summary>
        internal static string LoversWin {
            get {
                return ResourceManager.GetString("LoversWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini died.
        /// </summary>
        internal static string MiniDied {
            get {
                return ResourceManager.GetString("MiniDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modded by.
        /// </summary>
        internal static string Moddedby {
            get {
                return ResourceManager.GetString("Moddedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier Settings.
        /// </summary>
        internal static string ModifierSettings {
            get {
                return ResourceManager.GetString("ModifierSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Options....
        /// </summary>
        internal static string ModOptions {
            get {
                return ResourceManager.GetString("ModOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Options....
        /// </summary>
        internal static string MoreOptions {
            get {
                return ResourceManager.GetString("MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostor Role Settings.
        /// </summary>
        internal static string NeutralRoleSettings {
            get {
                return ResourceManager.GetString("NeutralRoleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players and roles at the end of the game.
        /// </summary>
        internal static string PlayersAndRolesAtTheEndOfTheGame {
            get {
                return ResourceManager.GetString("PlayersAndRolesAtTheEndOfTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press TAB or Page Number for more....
        /// </summary>
        internal static string PressTabOrPageNumberForMore {
            get {
                return ResourceManager.GetString("PressTabOrPageNumberForMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prop Hunt.
        /// </summary>
        internal static string PropHunt {
            get {
                return ResourceManager.GetString("PropHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prop Hunt Settings.
        /// </summary>
        internal static string PropHuntSettings {
            get {
                return ResourceManager.GetString("PropHuntSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosecutor Wins.
        /// </summary>
        internal static string ProsecutorWins {
            get {
                return ResourceManager.GetString("ProsecutorWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role and Modifier Rates.
        /// </summary>
        internal static string RoleAndModifierRates {
            get {
                return ResourceManager.GetString("RoleAndModifierRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Lighter / Darker.
        /// </summary>
        internal static string ShowLighterDarker {
            get {
                return ResourceManager.GetString("ShowLighterDarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Role Summary.
        /// </summary>
        internal static string ShowRoleSummary {
            get {
                return ResourceManager.GetString("ShowRoleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to.
        /// </summary>
        internal static string SpecialThanksTo {
            get {
                return ResourceManager.GetString("SpecialThanksTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping.
        /// </summary>
        internal static string Swapping {
            get {
                return ResourceManager.GetString("Swapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaps.
        /// </summary>
        internal static string Swaps {
            get {
                return ResourceManager.GetString("Swaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Jackal Wins.
        /// </summary>
        internal static string TeamJackal_ins {
            get {
                return ResourceManager.GetString("TeamJackal ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Lawyer wins with the client.
        /// </summary>
        internal static string TheLawyerWinsWithTheClient {
            get {
                return ResourceManager.GetString("TheLawyerWinsWithTheClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanilla Settings.
        /// </summary>
        internal static string TheOtherRolesSettings {
            get {
                return ResourceManager.GetString("TheOtherRolesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pursuer survived.
        /// </summary>
        internal static string ThePursuerSurvived {
            get {
                return ResourceManager.GetString("ThePursuerSurvived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiebreaker.
        /// </summary>
        internal static string Tiebreaker {
            get {
                return ResourceManager.GetString("Tiebreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOR Guesser.
        /// </summary>
        internal static string TorGuesser {
            get {
                return ResourceManager.GetString("TorGuesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOR Hide N Seek.
        /// </summary>
        internal static string TorHideNSeek {
            get {
                return ResourceManager.GetString("TorHideNSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOR Prop Hunt.
        /// </summary>
        internal static string TorPropHunt {
            get {
                return ResourceManager.GetString("TorPropHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse color id\nUsage: /color {id}.
        /// </summary>
        internal static string Unable {
            get {
                return ResourceManager.GetString("Unable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use scroll wheel if necessary.
        /// </summary>
        internal static string UseScrollWheelIfNecessary {
            get {
                return ResourceManager.GetString("UseScrollWheelIfNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanilla Settings.
        /// </summary>
        internal static string VanillaSettings {
            get {
                return ResourceManager.GetString("VanillaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vulture Wins.
        /// </summary>
        internal static string VultureWins {
            get {
                return ResourceManager.GetString("VultureWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was The.
        /// </summary>
        internal static string WasThe {
            get {
                return ResourceManager.GetString("WasThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in love with {0}.
        /// </summary>
        internal static string YouAreInLoveWith {
            get {
                return ResourceManager.GetString("YouAreInLoveWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Deputy Is {0}.
        /// </summary>
        internal static string YourDeputyIs {
            get {
                return ResourceManager.GetString("YourDeputyIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Sheriff is {0}.
        /// </summary>
        internal static string YourSheriffIs {
            get {
                return ResourceManager.GetString("YourSheriffIs", resourceCulture);
            }
        }
    }
}
